import {useEffect, useState} from 'react'

import dateFormat from 'dateformat'
import DateDiff from 'date-diff'

import Head from 'next/head'
import styles from '../styles/Home.module.css'

const interval = 1000 - Date.now() % 1000

// TODO 現状の時間が適当なので、ちゃんと休載期間を計算したtimeを表示する
// TODO クライアントPCから現在時刻を取得しているので、バックエンドから正しいJTCを取得する

function getNowStr() {
  const FORMAT = 'yyyy/mm/dd HH:MM:ss'
  return dateFormat(new Date(), FORMAT)
}

export default function Home() {
  const [time, setTime] = useState('')

  useEffect(() => {
    const timer = setTimeout(function main(){
      const suspended = new Date(2018, 11, 26)
      const now = new Date()
      const diff = new DateDiff(now, suspended)
      timer = setTimeout(main, interval)
      setTime(diff.seconds())
    }, interval)
    return () => clearTimeout(timer)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div>
          Hunter×Hunter 休載から
        </div>
        <div>
          {time} 秒
        </div>
        <div>経過</div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
